"""Catalogue des permissions applicatives (clés stables pour JSON roles.permissions)."""

PERMISSIONS_CATALOG = [
    {"key": "dashboard.view", "label": "Tableau de bord"},
    {"key": "dashboard.kpi", "label": "Tableau de bord — indicateurs agrégés (perso. + service si autorisé)"},
    {
        "key": "dashboard.kpi.org",
        "label": "Tableau de bord — volumes et délais au niveau organisation (courrier / RDV service)",
    },
    {"key": "mail.view", "label": "Courrier — consulter"},
    {"key": "mail.create", "label": "Courrier — saisir / téléverser"},
    {"key": "mail.update", "label": "Courrier — modifier métadonnées"},
    {"key": "mail.delete", "label": "Courrier — supprimer directement"},
    {"key": "mail.request_delete", "label": "Courrier — demander la suppression"},
    {"key": "mail.workflow.all", "label": "Courrier — toutes les actions workflow"},
    {"key": "mail.workflow.index", "label": "Courrier — indexer"},
    {"key": "mail.workflow.assign", "label": "Courrier — affecter"},
    {"key": "mail.workflow.treat", "label": "Courrier — traiter"},
    {"key": "mail.workflow.submit_validation", "label": "Courrier — soumettre validation (DG)"},
    {
        "key": "mail.workflow.submit_to_director",
        "label": "Courrier — transmettre à la direction (après traitement service)",
    },
    {
        "key": "mail.workflow.escalate_to_dg",
        "label": "Courrier — transmettre au DG pour avis final",
    },
    {"key": "mail.workflow.approve", "label": "Courrier — approuver"},
    {"key": "mail.workflow.reject", "label": "Courrier — rejeter"},
    {"key": "mail.workflow.hold", "label": "Courrier — mettre en attente"},
    {"key": "mail.workflow.resume", "label": "Courrier — reprendre"},
    {"key": "mail.workflow.request_changes", "label": "Courrier — demander compléments"},
    {"key": "mail.workflow.close", "label": "Courrier — clôturer (après validation)"},
    {"key": "mail.workflow.archive", "label": "Courrier — archiver (définitif)"},
    {"key": "mail.workflow.restore", "label": "Courrier — restaurer depuis les archives"},
    {"key": "appointments.view", "label": "RDV — consulter (liste, détail, statuts)"},
    {"key": "appointments.create", "label": "Gestion — créer un rendez-vous"},
    {"key": "appointments.update", "label": "Gestion — modifier (horaires, lieu, notes, reprogrammation)"},
    {"key": "appointments.delete", "label": "Gestion — annuler ou supprimer définitivement (master/director)"},
    {"key": "appointments.request_delete", "label": "Gestion — demander l’annulation (validation hiérarchique)"},
    {
        "key": "appointments.workflow.propose_slot",
        "label": "Gestion — proposer / reprogrammer un créneau (vérif. disponibilité, détection conflits, notif.)",
    },
    {
        "key": "appointments.workflow.agenda",
        "label": "Coordination — ordre du jour / points (invitations implicites via l’ODJ)",
    },
    {
        "key": "appointments.workflow.hierarchy_validate",
        "label": "Décision — valider ou refuser le RDV (DG, après créneau proposé — refus = annulation)",
    },
    {
        "key": "appointments.workflow.minutes",
        "label": "Post-RDV — rédiger le compte rendu (clôture documentaire)",
    },
    {
        "key": "appointments.workflow.tasks",
        "label": "Post-RDV — assigner et suivre les tâches liées au RDV",
    },
    {"key": "reception.view", "label": "Réception — consulter"},
    {"key": "reception.checkin", "label": "Réception — enregistrer visiteurs"},
    {"key": "deletion_requests.review", "label": "Demandes de suppression — examiner et trancher"},
    {"key": "users.view", "label": "Utilisateurs — consulter"},
    {"key": "users.manage", "label": "Utilisateurs — gérer"},
    {"key": "settings.self", "label": "Paramètres personnels"},
    {"key": "admin.roles", "label": "Admin — rôles et permissions"},
    {"key": "content.public_posts", "label": "Contenu — messages page d’accueil publique"},
    {"key": "admin.audit", "label": "Admin — journal d’audit"},
    {"key": "admin.notifications", "label": "Admin — centre notifications système"},
]

_MAIL_WORKFLOW_KEYS = [
    "mail.workflow.index",
    "mail.workflow.assign",
    "mail.workflow.treat",
    "mail.workflow.submit_validation",
    "mail.workflow.submit_to_director",
    "mail.workflow.escalate_to_dg",
    "mail.workflow.approve",
    "mail.workflow.reject",
    "mail.workflow.hold",
    "mail.workflow.resume",
    "mail.workflow.request_changes",
    "mail.workflow.close",
    "mail.workflow.archive",
    "mail.workflow.restore",
]

# Rôles système : master = tout ; director / admin = suppressions courrier & RDV, trancher demandes de suppression.
# Suppression des groupes (rôles) et création de groupes : réservé au master (API roles).
_DIRECTOR_LIKE_PERMISSIONS = [
    "dashboard.view",
    "dashboard.kpi",
    "dashboard.kpi.org",
    "mail.view",
    "mail.create",
    "mail.update",
    "mail.delete",
    "mail.request_delete",
    "mail.workflow.all",
    "appointments.view",
    "appointments.create",
    "appointments.update",
    "appointments.delete",
    "appointments.request_delete",
    "appointments.workflow.propose_slot",
    "appointments.workflow.agenda",
    "appointments.workflow.hierarchy_validate",
    "appointments.workflow.minutes",
    "appointments.workflow.tasks",
    "reception.view",
    "reception.checkin",
    "deletion_requests.review",
    "users.view",
    "settings.self",
]

DEFAULT_ROLE_PERMISSIONS = {
    "master": [p["key"] for p in PERMISSIONS_CATALOG],
    "director": list(_DIRECTOR_LIKE_PERMISSIONS),
    "admin": list(_DIRECTOR_LIKE_PERMISSIONS),
    # Secrétaire DG : consulter, affecter, planifier RDV, filtrer, traiter, soumettre validation — pas valider/rejeter (DG).
    "secretary": [
        "dashboard.view",
        "dashboard.kpi",
        "dashboard.kpi.org",
        "mail.view",
        "mail.create",
        "mail.update",
        "mail.request_delete",
        "mail.workflow.index",
        "mail.workflow.assign",
        "mail.workflow.treat",
        "mail.workflow.hold",
        "mail.workflow.resume",
        "mail.workflow.request_changes",
        "mail.workflow.close",
        "appointments.view",
        "appointments.create",
        "appointments.update",
        "appointments.request_delete",
        "appointments.workflow.propose_slot",
        "appointments.workflow.agenda",
        "appointments.workflow.minutes",
        "appointments.workflow.tasks",
        "settings.self",
    ],
    # Chef de service / agent : traitement courrier + coordination RDV opérationnelle (pas validation DG).
    "analyst": [
        "dashboard.view",
        "dashboard.kpi",
        "mail.view",
        "mail.update",
        "mail.workflow.treat",
        "mail.workflow.submit_validation",
        "mail.workflow.submit_to_director",
        "mail.workflow.hold",
        "mail.workflow.resume",
        "mail.workflow.request_changes",
        "appointments.view",
        "appointments.update",
        "appointments.request_delete",
        "appointments.workflow.propose_slot",
        "appointments.workflow.agenda",
        "appointments.workflow.minutes",
        "appointments.workflow.tasks",
        "settings.self",
    ],
    # Agent accueil : enregistrer / indexer / scanner, transmettre (affecter).
    "receptionist": [
        "dashboard.view",
        "dashboard.kpi",
        "dashboard.kpi.org",
        "reception.view",
        "reception.checkin",
        "appointments.view",
        "appointments.create",
        "appointments.update",
        "appointments.request_delete",
        "appointments.workflow.propose_slot",
        "appointments.workflow.agenda",
        "mail.view",
        "mail.create",
        "mail.update",
        "mail.workflow.index",
        "mail.workflow.assign",
        "settings.self",
    ],
    # Archiviste : archivage définitif et restauration.
    "archivist": [
        "dashboard.view",
        "mail.view",
        "mail.workflow.archive",
        "mail.workflow.restore",
        "settings.self",
    ],
    "guest": ["dashboard.view", "settings.self"],
}
